# Generated by Django 3.2 on 2021-06-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albums',
            name='duration',
        ),
    ]
